name: âš¡ Generate Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # Har 12 ghante me auto run
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest  # Ye GitHub ke cloud runner ke liye hai
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Awasthiutk564
          outputs: dist/snake.svg

      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
