name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"    # Har 12 ghante me auto run
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Awasthiutk564
          outputs: dist/snake.svg

      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output       # Final snake.svg yahi milega
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
